INSERT IGNORE INTO users (username, email, password, phone, full_name, gender, role, create_at, update_at) VALUES
                                                                                                               -- CUSTOMER (role = 'CUSTOMER')
                                                                                                               ('baobao1', 'baobao1@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234001', N'Bảo Bảo', 'MALE', 'CUSTOMER', NOW(), NOW()),
                                                                                                               ('triettriet1', 'triettriet1@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234002', N'Triết Triết', 'FEMALE', 'CUSTOMER', NOW(), NOW()),
                                                                                                               ('nguyennguyen1', 'nguyennguyen1@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234003', N'Nguyên Nguyên', 'MALE', 'CUSTOMER', NOW(), NOW()),
                                                                                                               ('thaothao1', 'thaothao1@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234004', N'Thảo Thảo', 'FEMALE', 'CUSTOMER',  NOW(), NOW()),
                                                                                                               -- TECHNICIAN (role = 'TECHNICIAN')
                                                                                                               ('baobao2', 'baobao2@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234005', N'Bảo Bảo', 'MALE', 'TECHNICIAN', NOW(), NOW()),
                                                                                                               ('triettriet2', 'triettriet2@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234006', N'Triết Triết', 'FEMALE', 'TECHNICIAN', NOW(), NOW()),
                                                                                                               ('nguyennguyen2', 'nguyennguyen2@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234007', N'Nguyên Nguyên', 'MALE', 'TECHNICIAN', NOW(), NOW()),
                                                                                                               ('thaothao2', 'thaothao2@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234008', N'Thảo Thảo', 'FEMALE', 'TECHNICIAN',  NOW(), NOW()),
                                                                                                               -- STAFF (role = 'STAFF')
                                                                                                               ('baobao3', 'baobao3@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234009', N'Bảo Bảo', 'MALE', 'STAFF', NOW(), NOW()),
                                                                                                               ('triettriet3', 'triettriet3@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234010', N'Triết Triết', 'FEMALE', 'STAFF', NOW(), NOW()),
                                                                                                               ('nguyennguyen3', 'nguyennguyen3@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234011', N'Nguyên Nguyên', 'MALE', 'STAFF', NOW(), NOW()),
                                                                                                               ('thaothao3', 'thaothao3@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234012', N'Thảo Thảo', 'FEMALE', 'STAFF', NOW(), NOW()),
                                                                                                               -- ADMIN (role = 'ADMIN')
                                                                                                               ('baobao4', 'baobao4@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234013', N'Bảo Bảo', 'MALE', 'ADMIN', NOW(), NOW()),
                                                                                                               ('triettriet4', 'triettriet4@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234014', N'Triết Triết', 'FEMALE', 'ADMIN', NOW(), NOW()),
                                                                                                               ('nguyennguyen4', 'nguyennguyen4@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234015', N'Nguyên Nguyên', 'MALE', 'ADMIN', NOW(), NOW()),
                                                                                                               ('thaothao4', 'thaothao4@example.com', '$2a$10$9ViHL2oWm7hurneJAixnW.6E2OUqWYaSrALzF3sVirp9.EwWnqncG', '0901234016', N'Thảo Thảo', 'FEMALE', 'ADMIN', NOW(), NOW());

INSERT INTO service_items (id, name, description) VALUES
                                                      (1, N'Cabin Air Filter', N'Replace or clean the cabin air filter'),
                                                      (2, N'Brake Fluid', N'Check or replace brake fluid'),
                                                      (3, N'Air Conditioning System', N'Check, clean, and maintain the A/C system'),
                                                      (4, N'Key Fob Battery', N'Check or replace the key fob battery (VFe34)'),
                                                      (5, N'T-Box Battery', N'Check or replace the T-Box battery'),
                                                      (6, N'Coolant for Battery/Electric Motor', N'Check or refill/replace the coolant'),
                                                      (7, N'Tires (pressure, wear, rotation, and balancing)', N'Inspect tires, rotate, and perform wheel balancing'),
                                                      (8, N'Brake Pads and Discs', N'Check wear of brake pads and discs'),
                                                      (9, N'Brake System Hoses and Connectors', N'Inspect for leaks, cracks, or damage to brake hoses'),
                                                      (10, N'Drivetrain (Electric Motor and Gearbox)', N'Check operating condition'),
                                                      (11, N'Suspension System', N'Inspect shock absorbers, springs, and linkages'),
                                                      (12, N'Drive Shaft', N'Inspect drive shaft and universal joints'),
                                                      (13, N'Ball Joints', N'Inspect ball joints and tie-rod ends'),
                                                      (14, N'Steering Rack and Linkages', N'Inspect steering system components'),
                                                      (15, N'Coolant Hoses', N'Inspect for leaks or cracks in coolant hoses (VFe34)'),
                                                      (16, N'Battery / High-Voltage Battery', N'Check battery condition and cooling fan operation'),
                                                      (17, N'High-Voltage Electrical Cables', N'Inspect high-voltage electrical cables'),
                                                      (18, N'Charging Port', N'Inspect and clean the charging port'),
                                                      (19, N'12V Battery / 12V Battery Condition', N'Check condition of the 12V battery'),
                                                      (20, N'Wiper Blades / Windshield Washer Fluid', N'Check and refill washer fluid, replace wipers if necessary'),
                                                      (21, N'Rust / Corrosion Underbody Inspection', N'Inspect the underbody for rust or corrosion'),
                                                      (22, N'Wheels (Damage, Deformation, Cracks)', N'Inspect wheels for damage or cracks'),
                                                      (23, N'Axle and Suspension System', N'Inspect axle and suspension components'),
                                                      (24, N'Drive Shaft and Dust Boots', N'Inspect drive shaft and dust boots'),
                                                      (25, N'Suspension Ball Joints', N'Inspect suspension ball joints'),
                                                      (26, N'Steering Mechanism and Ball Joints', N'Inspect steering mechanism and ball joints'),
                                                      (27, N'Coolant Hoses Inspection', N'Inspect coolant hoses (VF5–9)');

INSERT IGNORE INTO vehicle_models (id, name, model_year) VALUES
                                                             (1, N'VFe34', N'2021'),
                                                             (2, N'VF 3', N'2024'),
                                                             (3, N'VF 5', N'2023'),
                                                             (4, N'VF 6', N'2023'),
                                                             (5, N'VF 7', N'2024'),
                                                             (6, N'VF 8', N'2022'),
                                                             (7, N'VF 9', N'2022');


INSERT IGNORE INTO service_centers (name, address, district, city, phone)
VALUES
    ('Vin3S Showroom Hoc Mon Center', '166 Ly Thuong Kiet, Quarter 3, Hoc Mon Town', 'Hoc Mon District', 'Ho Chi Minh City', '0762718718'),
    ('Vin3S Showroom 39A Ha Huy Giap', '39A Ha Huy Giap Street', 'District 12', 'Ho Chi Minh City', '0702721721'),
    ('Vin3S Showroom 314 Nguyen Anh Thu - Hiep Thanh', '314A Nguyen Anh Thu Street, Hiep Thanh Ward', 'District 12', 'Ho Chi Minh City', '0796621621'),
    ('Vin3S Showroom Nha Be', '2250 Huynh Tan Phat Street, Phu Xuan Commune', 'Nha Be District', 'Ho Chi Minh City', '0946143939'),
    ('Vin3S Showroom Cu Chi Center', '158 TL8, Cu Chi Town', 'Cu Chi District', 'Ho Chi Minh City', '0904404692'),

       INSERT IGNORE INTO spare_parts
(part_number, name, unit_price, quantity_in_stock, minimum_stock_level, category_name, category_code, create_at, created_by, update_at, updated_by)
VALUES
-- === SPARE PARTS FOR VF 3 ===
('FLT-VF3', N'Cabin air filter VF 3', 490000.00, 50, 10, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VF3', N'Brake fluid DOT 4 (VF 3)', 380000.00, 30, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-KEY-GEN', N'Key battery CR2032 (Common)', 45000.00, 300, 50, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'), -- Common
('BAT-TBOX-VF3', N'T-Box battery VF 3', 650000.00, 20, 5, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VF3', N'12V battery AGM 60Ah (VF 3)', 4300000.00, 15, 5, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VF3', N'Front brake pads VF 3', 990000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VF3', N'Rear brake pads VF 3', 920000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VF3', N'Front brake disc VF 3', 1580000.00, 10, 2, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VF3', N'Front shock absorber VF 3', 1950000.00, 10, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VF3', N'Lower ball joint VF 3', 780000.00, 15, 5, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VF3', N'Outer tie rod end VF 3', 720000.00, 15, 5, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VF3', N'CV joint VF 3', 2450000.00, 5, 2, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VF3', N'Main coolant hose VF 3', 520000.00, 10, 3, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VF3', N'A/C expansion valve VF 3', 990000.00, 5, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VF3', N'Charging cable VF 3', 6200000.00, 3, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VF3', N'Main HV fuse VF 3', 1450000.00, 5, 2, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VF3', N'Tire VF 3 (175/75R16)', 1850000.00, 30, 10, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VF3', N'TPMS valve sensor VF 3', 850000.00, 40, 10, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VF3', N'Washer fluid pump VF 3', 520000.00, 10, 3, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VF3', N'Wiper blade set VF 3', 480000.00, 20, 5, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),

-- === SPARE PARTS FOR VF 5 ===
('FLT-VF5', N'Cabin air filter VF 5', 490000.00, 50, 10, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VF5', N'Brake fluid DOT 4 (VF 5)', 380000.00, 30, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-COOL-VF5', N'EV Coolant Type 1 (VF 5)', 650000.00, 20, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-TBOX-VF5', N'T-Box battery VF 5', 680000.00, 20, 5, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VF5', N'12V battery AGM 60Ah (VF 5)', 4300000.00, 15, 5, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VF5', N'Front brake pads VF 5', 1020000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VF5', N'Rear brake pads VF 5', 960000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VF5', N'Front brake disc VF 5', 1620000.00, 10, 2, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VF5', N'Front shock absorber VF 5', 2020000.00, 10, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VF5', N'Lower ball joint VF 5', 820000.00, 15, 5, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VF5', N'Outer tie rod end VF 5', 760000.00, 15, 5, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VF5', N'CV joint VF 5', 2580000.00, 5, 2, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VF5', N'Main coolant hose VF 5', 550000.00, 10, 3, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VF5', N'A/C expansion valve VF 5', 1020000.00, 5, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VF5', N'Charging cable VF 5', 6400000.00, 3, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VF5', N'Main HV fuse VF 5', 1520000.00, 5, 2, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VF5', N'Tire VF 5', 2050000.00, 30, 10, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VF5', N'TPMS valve sensor VF 5', 860000.00, 40, 10, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VF5', N'Washer fluid pump VF 5', 540000.00, 10, 3, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VF5', N'Wiper blade set VF 5', 500000.00, 20, 5, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'), -- Thêm (ước tính)

-- === SPARE PARTS FOR VF 6 ===
('FLT-VF6', N'Cabin air filter VF 6', 520000.00, 40, 10, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VF6', N'Brake fluid DOT 4 (VF 6)', 380000.00, 30, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-COOL-VF6', N'EV Coolant Type 1 (VF 6)', 650000.00, 20, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-TBOX-VF6', N'T-Box battery VF 6', 680000.00, 20, 5, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VF6', N'Wiper blade set VF 6', 720000.00, 30, 10, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VF6', N'12V battery AGM 70Ah (VF 6)', 4700000.00, 10, 3, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VF6', N'Front brake pads VF 6', 1150000.00, 15, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VF6', N'Rear brake pads VF 6', 1080000.00, 15, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VF6', N'Front brake disc VF 6', 1850000.00, 5, 2, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VF6', N'Front shock absorber VF 6', 2200000.00, 5, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VF6', N'Lower ball joint VF 6', 850000.00, 10, 3, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VF6', N'Outer tie rod end VF 6', 790000.00, 10, 3, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VF6', N'CV joint VF 6', 2700000.00, 3, 1, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VF6', N'Main coolant hose VF 6', 570000.00, 8, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VF6', N'A/C expansion valve VF 6', 1050000.00, 3, 1, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VF6', N'Charging cable VF 6', 6500000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VF6', N'Main HV fuse VF 6', 1550000.00, 3, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VF6', N'Tire VF 6', 2450000.00, 20, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VF6', N'TPMS valve sensor VF 6', 860000.00, 30, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VF6', N'Washer fluid pump VF 6', 540000.00, 8, 2, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),

-- === SPARE PARTS FOR VF 7 ===
('FLT-VF7', N'Cabin air filter VF 7', 520000.00, 40, 10, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VF7', N'Brake fluid DOT 4 (VF 7)', 380000.00, 30, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-COOL-VF7', N'EV Coolant Type 1 (VF 7)', 650000.00, 20, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-TBOX-VF7', N'T-Box battery VF 7', 680000.00, 20, 5, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VF7', N'Wiper blade set VF 7', 730000.00, 30, 10, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VF7', N'12V battery AGM 70Ah (VF 7)', 4700000.00, 10, 3, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VF7', N'Front brake pads VF 7', 1160000.00, 15, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VF7', N'Rear brake pads VF 7', 1090000.00, 15, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VF7', N'Front brake disc VF 7', 1860000.00, 5, 2, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VF7', N'Front shock absorber VF 7', 2250000.00, 5, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VF7', N'Lower ball joint VF 7', 860000.00, 10, 3, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VF7', N'Outer tie rod end VF 7', 800000.00, 10, 3, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VF7', N'CV joint VF 7', 2750000.00, 3, 1, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VF7', N'Main coolant hose VF 7', 580000.00, 8, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VF7', N'A/C expansion valve VF 7', 1060000.00, 3, 1, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VF7', N'Charging cable VF 7', 6600000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VF7', N'Main HV fuse VF 7', 1560000.00, 3, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VF7', N'Tire VF 7', 2750000.00, 20, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VF7', N'TPMS valve sensor VF 7', 860000.00, 30, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VF7', N'Washer fluid pump VF 7', 540000.00, 8, 2, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),

-- === SPARE PARTS FOR VFe34 ===
('FLT-VFE34', N'Cabin air filter VFe34', 520000.00, 30, 5, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VFE34', N'Brake fluid DOT 4 (VFe34)', 380000.00, 20, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-COOL-VFE34', N'EV Coolant Type 2 (VFe34)', 680000.00, 15, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-TBOX-VFE34', N'T-Box battery VFe34', 700000.00, 10, 2, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VFE34', N'12V battery AGM 70Ah (VFe34)', 4700000.00, 8, 2, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VFE34', N'Front brake pads VFe34', 1380000.00, 10, 3, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VFE34', N'Rear brake pads VFe34', 1280000.00, 10, 3, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VFE34', N'Front brake disc VFe34', 2150000.00, 5, 1, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VFE34', N'Front shock absorber VFe34', 2500000.00, 3, 1, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VFE34', N'Lower ball joint VFe34', 900000.00, 8, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VFE34', N'Outer tie rod end VFe34', 850000.00, 8, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VFE34', N'CV joint VFe34', 3000000.00, 2, 1, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VFE34', N'Main coolant hose VFe34', 600000.00, 5, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VFE34', N'A/C expansion valve VFe34', 1100000.00,   2, 1, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VFE34', N'Charging cable VFe34', 6800000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VFE34', N'Main HV fuse VFe34', 1600000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VFE34', N'Tire VFe34', 2950000.00, 15, 3, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VFE34', N'TPMS valve sensor VFe34', 860000.00, 20, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VFE34', N'Washer fluid pump VFe34', 540000.00, 5, 2, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VFE34', N'Wiper blade set VFe34', 550000.00, 20, 5, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'), -- Thêm (ước tính)

-- === SPARE PARTS FOR VF 8 ===
('FLT-VF8', N'Cabin air filter VF 8', 530000.00, 30, 5, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VF8', N'Brake fluid DOT 4 (VF 8)', 380000.00, 20, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-COOL-VF8', N'EV Coolant Type 2 (VF 8)', 690000.00, 15, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-TBOX-VF8', N'T-Box battery VF 8', 710000.00, 10, 2, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VF8', N'12V battery AGM 70Ah (VF 8)', 4700000.00, 8, 2, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VF8', N'Front brake pads VF 8', 1390000.00, 10, 3, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VF8', N'Rear brake pads VF 8', 1290000.00, 10, 3, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VF8', N'Front brake disc VF 8', 2160000.00, 5, 1, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VF8', N'Front shock absorber VF 8', 2550000.00, 3, 1, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VF8', N'Lower ball joint VF 8', 910000.00, 8, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VF8', N'Outer tie rod end VF 8', 860000.00, 8, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VF8', N'CV joint VF 8', 3050000.00, 2, 1, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VF8', N'Main coolant hose VF 8', 610000.00, 5, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VF8', N'A/C expansion valve VF 8', 1110000.00, 2, 1, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VF8', N'Charging cable VF 8', 6900000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VF8', N'Main HV fuse VF 8', 1610000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VF8', N'Tire VF 8', 3600000.00, 15, 3, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VF8', N'TPMS valve sensor VF 8', 860000.00, 20, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VF8', N'Washer fluid pump VF 8', 540000.00, 5, 2, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VF8', N'Wiper blade set VF 8', 750000.00, 20, 5, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'), -- Thêm (ước tính)

-- === SPARE PARTS FOR VF 9 ===
('FLT-VF9', N'Cabin air filter VF 9', 550000.00, 30, 5, N'Filters', 'FILTER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-BRK-VF9', N'Brake fluid DOT 4 (VF 9)', 380000.00, 20, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('FLD-COOL-VF9', N'EV Coolant Type 2 (VF 9)', 700000.00, 15, 5, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-TBOX-VF9', N'T-Box battery VF 9', 720000.00, 10, 2, N'Batteries & Electronics', 'ELECTRONIC', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BAT-12V-VF9', N'12V battery AGM 70Ah (VF 9)', 4700000.00, 8, 2, N'Battery', 'BATTERY', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-F-VF9', N'Front brake pads VF 9', 1400000.00, 10, 3, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-PAD-R-VF9', N'Rear brake pads VF 9', 1300000.00, 10, 3, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-DISC-F-VF9', N'Front brake disc VF 9', 2170000.00, 5, 1, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-SHOCK-F-VF9', N'Front shock absorber VF 9', 2600000.00, 3, 1, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-BALLJ-VF9', N'Lower ball joint VF 9', 920000.00, 8, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('SUS-TIEROD-VF9', N'Outer tie rod end VF 9', 870000.00, 8, 2, N'Suspension & Steering', 'SUSPENSION', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('DRV-AXLE-VF9', N'CV joint VF 9', 3100000.00, 2, 1, N'Drivetrain', 'DRIVETRAIN', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('COOL-HOSE-VF9', N'Main coolant hose VF 9', 620000.00, 5, 2, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('AC-VALVE-VF9', N'A/C expansion valve VF 9', 1120000.00, 2, 1, N'Cooling & A/C System', 'COOLING', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-CABLE-VF9', N'Charging cable VF 9', 7000000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('HV-FUSE-VF9', N'Main HV fuse VF 9', 1620000.00, 2, 1, N'High Voltage System', 'HIGH_VOLTAGE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TIRE-VF9', N'Tire VF 9', 4200000.00, 15, 3, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WHL-TPMS-VF9', N'TPMS valve sensor VF 9', 860000.00, 20, 5, N'Tires & Wheels', 'WHEEL', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-PUMP-VF9', N'Washer fluid pump VF 9', 540000.00, 5, 2, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('WPR-BLD-VF9', N'Wiper blade set VF 9', 780000.00, 20, 5, N'Wipers & Washers', 'WIPER', NOW(), 'SYSTEM', NOW(), 'SYSTEM'), -- Thêm (ước tính)

-- [THÊM MỚI]
-- === SPARE PARTS CHO HẠNG MỤC BỊ THIẾU (Ống phanh, Gỉ sét) - THEO TỪNG MODEL ===
('BRK-HOSE-VF3', N'Bộ ống dầu phanh VF 3', 500000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VF3', N'Hóa chất phủ gầm VF 3 (Lon)', 300000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-HOSE-VF5', N'Bộ ống dầu phanh VF 5', 550000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VF5', N'Hóa chất phủ gầm VF 5 (Lon)', 300000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-HOSE-VF6', N'Bộ ống dầu phanh VF 6', 570000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VF6', N'Hóa chất phủ gầm VF 6 (Lon)', 350000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-HOSE-VF7', N'Bộ ống dầu phanh VF 7', 580000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VF7', N'Hóa chất phủ gầm VF 7 (Lon)', 350000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-HOSE-VFE34', N'Bộ ống dầu phanh VFe34', 600000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VFE34', N'Hóa chất phủ gầm VFe34 (Lon)', 400000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-HOSE-VF8', N'Bộ ống dầu phanh VF 8', 610000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VF8', N'Hóa chất phủ gầm VF 8 (Lon)', 400000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('BRK-HOSE-VF9', N'Bộ ống dầu phanh VF 9', 620000.00, 20, 5, N'Brake System', 'BRAKE', NOW(), 'SYSTEM', NOW(), 'SYSTEM'),
('CHEM-RUST-VF9', N'Hóa chất phủ gầm VF 9 (Lon)', 400000.00, 30, 10, N'Liquids & Chemicals', 'LIQUID', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

