-- ---------------------------------
-- --- MODEL: VF 7 (model_id=5) ---
-- --- IDs Phụ tùng (từ Phần 8): FLT=61, BRK=62, COOL=63, TBOX=64, GẠT MƯA=65, AC=75, LỐP=78, MÁ PHANH F=67
-- --- IDs Mới: ỐNG PHANH=147, GỈ SÉT=148
-- ---------------------------------

-- 9.5.A: Dữ liệu VF 7 theo lịch trình
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) VALUES
                                                                                                                                                     (5, 12000, 1, 674000, 'REPLACE', 61, 1), (5, 12000, 20, 27500, 'CHECK', null, 0), (5, 12000, 3, 49500, 'CHECK', null, 0), (5, 12000, 5, 27500, 'CHECK', null, 0), (5, 12000, 6, 38500, 'CHECK', null, 0), (5, 12000, 2, 49500, 'CHECK', null, 0), (5, 12000, 7, 49500, 'CHECK', null, 0), (5, 12000, 22, 49500, 'CHECK', null, 0), (5, 12000, 8, 49500, 'CHECK', null, 0), (5, 12000, 9, 38500, 'CHECK', null, 0), (5, 12000, 10, 49500, 'CHECK', null, 0), (5, 12000, 11, 49500, 'CHECK', null, 0), (5, 12000, 12, 38500, 'CHECK', null, 0), (5, 12000, 13, 38500, 'CHECK', null, 0), (5, 12000, 14, 49500, 'CHECK', null, 0), (5, 12000, 27, 38500, 'CHECK', null, 0), (5, 12000, 16, 55000, 'CHECK', null, 0), (5, 12000, 17, 49500, 'CHECK', null, 0), (5, 12000, 18, 27500, 'CHECK', null, 0), (5, 12000, 19, 38500, 'CHECK', null, 0), (5, 12000, 21, 38500, 'CHECK', null, 0);
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 24000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 12000;
UPDATE model_package_items SET price = 622000, action_type = 'REPLACE', included_spare_part_id = 62, included_quantity = 1 WHERE vehicle_model_id = 5 AND milestone_km = 24000 AND service_item_id = 2;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 36000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 12000;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 48000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 24000;
UPDATE model_package_items SET price = 880000, action_type = 'REPLACE', included_spare_part_id = 65, included_quantity = 1 WHERE vehicle_model_id = 5 AND milestone_km = 48000 AND service_item_id = 20;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 60000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 12000;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 72000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 24000;
UPDATE model_package_items SET price = 1120000, action_type = 'REPLACE', included_spare_part_id = 64, included_quantity = 1 WHERE vehicle_model_id = 5 AND milestone_km = 72000 AND service_item_id = 5;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 84000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 12000;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 96000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 48000;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 108000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 12000;
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) SELECT 5, 120000, service_item_id, price, action_type, included_spare_part_id, included_quantity FROM model_package_items WHERE vehicle_model_id = 5 AND milestone_km = 24000;
UPDATE model_package_items SET price = 1068000, action_type = 'REPLACE', included_spare_part_id = 63, included_quantity = 1 WHERE vehicle_model_id = 5 AND milestone_km = 120000 AND service_item_id = 6;
UPDATE model_package_items SET price = 1390000, action_type = 'REPLACE', included_spare_part_id = 75, included_quantity = 1 WHERE vehicle_model_id = 5 AND milestone_km = 120000 AND service_item_id = 3;

-- 9.5.B: Dữ liệu VF 7 "Nâng cấp" (Mốc 1km)
INSERT INTO model_package_items (vehicle_model_id, milestone_km, service_item_id, price, action_type, included_spare_part_id, included_quantity) VALUES
                                                                                                                                                     (5, 1, 20, 880000, 'REPLACE', 65, 1),
                                                                                                                                                     (5, 1, 3, 1390000, 'REPLACE', 75, 1),
                                                                                                                                                     (5, 1, 5, 1120000, 'REPLACE', 64, 1),
                                                                                                                                                     (5, 1, 6, 1068000, 'REPLACE', 63, 1),
                                                                                                                                                     (5, 1, 2, 622000, 'REPLACE', 62, 1),
                                                                                                                                                     (5, 1, 7, 11200000, 'REPLACE', 78, 4), -- (FIXED) Lốp (ID 78) * 4
                                                                                                                                                     (5, 1, 22, 1060000, 'REPLACE', 79, 1),
                                                                                                                                                     (5, 1, 8, 2450000, 'REPLACE', 67, 1), -- (FIXED) Má phanh (ID 67 - F) + (ID 68 - R) -> Dùng 1 set F
                                                                                                                                                     (5, 1, 9, 780000, 'REPLACE', 147, 1), -- (FIXED) Ống phanh -> ID 147
                                                                                                                                                     (5, 1, 10, 3250000, 'REPLACE', 73, 1),
                                                                                                                                                     (5, 1, 11, 2650000, 'REPLACE', 70, 1),
                                                                                                                                                     (5, 1, 12, 3250000, 'REPLACE', 73, 1),
                                                                                                                                                     (5, 1, 13, 1060000, 'REPLACE', 71, 1),
                                                                                                                                                     (5, 1, 14, 1100000, 'REPLACE', 72, 1),
                                                                                                                                                     (5, 1, 27, 780000, 'REPLACE', 74, 1),
                                                                                                                                                     (5, 1, 16, 2060000, 'REPLACE', 77, 1),
                                                                                                                                                     (5, 1, 17, 7600000, 'REPLACE', 76, 1),
                                                                                                                                                     (5, 1, 18, 7600000, 'REPLACE', 76, 1),
                                                                                                                                                     (5, 1, 19, 4900000, 'REPLACE', 66, 1),
                                                                                                                                                     (5, 1, 21, 600000, 'REPLACE', 148, 1); -- (FIXED) Gỉ sét gầm -> ID 148
